

"""MAP"""
MAP_FRAME_ROW = 0
MAP_FRAME_COLUMN = 0
MAP_FRAME_ROWSPAN = 1
MAP_FRAME_COLUMNSPAN = 1


MAP_WIDTH = 400
MAP_HEIGHT = 400
MAP_CORNER_RADIUS = 0

MAP_WIDGET_ROW = 0
MAP_WIDGET_COLUMN = 0
MAP_STICKY = "W"

""" MAP LOCATION"""

TMU_LAT = 43.65897373429778
TMU_LON = -79.37932931217927

LAT_FOR_MAP = TMU_LAT
LON_FOR_MAP = TMU_LON

""" MAP WAYPOINT """




"""SCROLLS"""

"""FRAME SETTINGS"""
SCROLL_FRAME_ROW = 0
SCROLL_FRAME_COLUMN = 1
SCROLL_FRAME_ROWSPAN = 1
SCROLL_FRAME_COLUMNSPAN = 1

#"""EVENT SCROLL SETTINGS"""


#"""ACTION FEED SCROLL SETTINGS"""


"""""""""ACTION CONSOLE FRAME"""""""""

ACTION_CONSOLE_FRAME_ROW = 1
ACTION_CONSOLE_FRAME_COLUMN = 0
ACTION_CONSOLE_FRAME_ROWSPAN = 1
ACTION_CONSOLE_FRAME_COLUMNSPAN =  2

ACTION_CONSOLE_FRAME_INNER_PADDING_X = 5
ACTION_CONSOLE_FRAME_INNER_PADDING_Y = 2

ACTION_CONSOLE_FRAME_STICKY = "W"


"""DRIVE SWITCH FRAME"""
DRIVE_SWITCH_FRAME_ROW = 1
DRIVE_SWITCH_FRAME_COLUMN = 1
DRIVE_SWITCH_FRAME_ROWSPAN = 1
DRIVE_SWITCH_FRAME_COLUMNSPAN = 1
DRIVE_SWITCH_FRAME_STICKY = "E"

"""TEXT FIELD LABELS """
TEXT_FIELD_LABEL_FRAME_ROW = 0
TEXT_FIELD_LABEL_FRAME_COLUMN = 0

TEXT_FIELD_LABEL_FRAME_INNER_PADDING_X = 5
TEXT_FIELD_LABEL_FRAME_INNER_PADDING_Y = 5

"""TEXT FIELDS """

TEXT_FIELDS_FRAME_ROW = 0
TEXT_FIELDS_FRAME_COLUMN = 1

TEXT_FIELDS_FRAME_INNER_PADDING_X = 5
TEXT_FIELDS_FRAME_INNER_PADDING_Y = 5

""" ACTION CONSOLE BUTTONS """

BUTTON_FRAME_ROW = 0
BUTTON_FRAME_COLUMN = 2
BUTTON_FRAME_ROWSPAN = 1
BUTTON_FRAME_COLUMNSPAN =  2

BUTTON_FRAME_INNER_PADDING_X = 2
BUTTON_FRAME_INNER_PADDING_Y = 5

ACTION_CONSOLE_BUTTON_MATRIX = [[0,0],[1,0],[0,1],[1,1]]

""" ACTION CONSOLE ROVER INFO LABELS"""

ROVER_INFO_LABEL_FRAME_ROW = 1
ROVER_INFO_LABEL_FRAME_COLUMN = 1
ROVER_INFO_LABEL_FRAME_ROWSPAN = 1
ROVER_INFO_LABEL_FRAME_COLUMNSPAN =  1

ROVER_INFO_FRAME_INNER_PADDING_X = 2
ROVER_INFO_FRAME_INNER_PADDING_Y= 2

PADDING = 2

""" ROVER INFO LABEL LABELS """

ROVER_LAT_LABEL_ROW = 0
ROVER_LAT_LABEL_COLUMN = 0
ROVER_LAT_LABEL_PADDING_X = PADDING
ROVER_LAT_LABEL_PADDING_Y = PADDING

ROVER_LON_LABEL_ROW = 1
ROVER_LON_LABEL_COLUMN = 0
ROVER_LON_LABEL_PADDING_X = PADDING
ROVER_LON_LABEL_PADDING_Y = PADDING

ROVER_ARB_LABEL_ROW = 2
ROVER_ARB_LABEL_COLUMN = 0
ROVER_ARB_LABEL_PADDING_X = PADDING
ROVER_ARB_LABEL_PADDING_Y = PADDING

""" ROVER INFO DATA LABELS """

ROVER_LAT_DATA_ROW = 0
ROVER_LAT_DATA_COLUMN = 1
ROVER_LAT_DATA_PADDING_X = PADDING
ROVER_LAT_DATA_PADDING_Y = PADDING

ROVER_LON_DATA_ROW = 1
ROVER_LON_DATA_COLUMN = 1
ROVER_LON_DATA_PADDING_X = PADDING
ROVER_LON_DATA_PADDING_Y = PADDING

ROVER_ARB_DATA_ROW = 2
ROVER_ARB_DATA_COLUMN = 1
ROVER_ARB_DATA_PADDING_X = PADDING
ROVER_ARB_DATA_PADDING_Y = PADDING



""" CONNECTION/STATUS BAR"""
STATUS_BAR_FRAME_ROW = 2
STATUS_BAR_FRAME_COLUMN = 0
STATUS_BAR_FRAME_ROWSPAN = 1
STATUS_BAR_FRAME_COLUMNSPAN =  2
STATUS_BAR_FRAME_STICKY = "EW"

STATUS_BAR_FRAME_INNER_PADDING_X = 2
STATUS_BAR_FRAME_INNER_PADDING_Y= 2




_FRAME_ROW = 0
_FRAME_COLUMN = 0
_FRAME_ROWSPAN = 1
_FRAME_COLUMNSPAN =  1
