

"""MAP"""
MAP_FRAME_ROW = 0
MAP_FRAME_COLUMN = 0
MAP_FRAME_ROWSPAN = 1
MAP_FRAME_COLUMNSPAN = 1


MAP_WIDTH = 400
MAP_HEIGHT = 400
MAP_CORNER_RADIUS = 0

"""SCROLLS"""

"""FRAME SETTINGS"""
SCROLL_FRAME_ROW = 0
SCROLL_FRAME_COLUMN = 1
SCROLL_FRAME_ROWSPAN = 1
SCROLL_FRAME_COLUMNSPAN = 1

#"""EVENT SCROLL SETTINGS"""


#"""ACTION FEED SCROLL SETTINGS"""


"""""""""ACTION CONSOLE FRAME"""""""""

ACTION_CONSOLE_FRAME_ROW = 1
ACTION_CONSOLE_FRAME_COLUMN = 0
ACTION_CONSOLE_FRAME_ROWSPAN = 1
ACTION_CONSOLE_FRAME_COLUMNSPAN =  2

ACTION_CONSOLE_FRAME_INNER_PADDING_X = 2
ACTION_CONSOLE_FRAME_INNER_PADDING_Y = 2


"""TEXT FIELD LABELS """
TEXT_FIELD_LABEL_FRAME_ROW = 0
TEXT_FIELD_LABEL_FRAME_COLUMN = 0

TEXT_FIELD_LABEL_FRAME_INNER_PADDING_X = 5
TEXT_FIELD_LABEL_FRAME_INNER_PADDING_Y = 5

"""TEXT FIELDS """

TEXT_FIELDS_FRAME_ROW = 0
TEXT_FIELDS_FRAME_COLUMN = 1

TEXT_FIELDS_FRAME_INNER_PADDING_X = 5
TEXT_FIELDS_FRAME_INNER_PADDING_Y = 5

""" ACTION CONSOLE BUTTONS """

BUTTON_FRAME_ROW = 0
BUTTON_FRAME_COLUMN = 2
BUTTON_FRAME_ROWSPAN = 1
BUTTON_FRAME_COLUMNSPAN =  2

BUTTON_FRAME_INNER_PADDING_X = 2
BUTTON_FRAME_INNER_PADDING_Y = 5

ACTION_CONSOLE_BUTTON_MATRIX = [[0,0],[1,0],[0,1],[1,1]]




_FRAME_ROW = 0
_FRAME_COLUMN = 0
_FRAME_ROWSPAN = 1
_FRAME_COLUMNSPAN =  1
