# VARIABLES TO SET THE WINDOW SIZE & POSITION ON THE SCREEN
WIN_WIDTH = 800
WIN_HEIGHT = 620
WIN_X_POSITION = 10
WIN_Y_POSITION = 10
SETUP_STRING = f'{WIN_WIDTH}x{WIN_HEIGHT}+{WIN_X_POSITION}+{WIN_Y_POSITION}'
