IDLE_WINDOW_SIZE = 3
IDLE_ARUCO_CONFIRM_THRESHOLD = 0.5

ARUCO_COFIRM_WINDOW_SIZE = 3
ACTIVE_ARUCO_CONFIRM_ACTIVATION = 0.5
ARUCO_COFIRM_TIMEOUT = 0.35

RESET_WINDOW_SIZE = 10
RESET_TO_IDLE_CONFIRM_THRESHOLD = 0.3
RESET_TO_IDLE_CONFIRM_TIMEOUT = 0.25
#if x number of frames are NOT activated/detected, reset everything