IDLE_WINDOW_SIZE = 3
IDLE_CONFIRM_THRESHOLD = 0.5

ARUCO_COFIRM_WINDOW_SIZE = 5
ARUCO_COFIRM_CONFIRM_THRESHOLD = 0.6
ARUCO_COFIRM_TIMEOUT = 0.7

RESET_WINDOW_SIZE = 10
RESET_CONFIRM_THRESHOLD = 0.4 
#if activation than 4 frames, reset everything
RESET_CONFIRM_TIMEOUT = 0.4